# Generated by Django 3.1.2 on 2020-10-31 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201031_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_id',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
