# Generated by Django 3.1.2 on 2020-12-03 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20201031_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='')),
                ('access_token', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('expires', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='like_time',
            new_name='create_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='like_date',
        ),
        migrations.AddField(
            model_name='post',
            name='update_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('friend_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_from', to=settings.AUTH_USER_MODEL)),
                ('friend_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
