# Generated by Django 3.1.2 on 2020-12-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='tag_info',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
    ]
